# Generated by Django 6.0.6 on 2026-08-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('subject', models.CharField(max_length=200, verbose_name='asunto')),
                ('body', models.TextField(verbose_name='mensaje')),
                ('status', models.CharField(choices=[('NEW', 'Nuevo'), ('READ', 'Leído'), ('RESOLVED', 'Resuelto')], default='NEW', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de envío')),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-created_at'],
            },
        ),
    ]
