/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/csrf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Semilla de cookie CSRF
         * @description Endpoint público que genera y establece la cookie CSRF para clientes de navegador.
         */
        get: operations["auth_csrf_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar sesión (Login)
         * @description Recibe el correo electrónico y la contraseña. Establece cookies HttpOnly de acceso y refresco, y devuelve un mensaje sin exponer tokens.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cerrar sesión (Logout)
         * @description Elimina las cookies HttpOnly del token de acceso y refresco.
         */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener perfil del usuario autenticado
         * @description Lee el token JWT enviado en las cabeceras y devuelve los datos personales del usuario conectado.
         */
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/phone/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Actualizar teléfono del perfil autenticado
         * @description Valida y normaliza el teléfono móvil chileno usado para el checkout.
         */
        patch: operations["auth_me_phone_partial_update"];
        trace?: never;
    };
    "/api/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar un nuevo cliente
         * @description Permite a los usuarios de la tienda crear una cuenta de cliente. Crea el usuario y su perfil de despacho de forma automática.
         */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refrescar token de acceso
         * @description Lee el token de refresco desde la cookie HttpOnly, requiere CSRF, y renueva la cookie de acceso sin devolver tokens en el body.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ver mi carrito de compras
         * @description Devuelve el carrito del usuario con subtotales, envío y total; con ?comuna={id} el envío usa la autoridad de precios del backend.
         */
        get: operations["cart_me_retrieve"];
        put?: never;
        /**
         * Añadir o actualizar producto en el carrito
         * @description Recibe un product_id y la cantidad. Si el producto ya está en el carro, suma la cantidad; si no, lo añade.
         */
        post: operations["cart_me_create"];
        /**
         * Remover o disminuir producto del carrito
         * @description Recibe un product_id y la cantidad a quitar. Si la cantidad del carro llega a cero o menos, el ítem se elimina por completo.
         */
        delete: operations["cart_me_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["categories_list"];
        put?: never;
        post: operations["categories_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["categories_retrieve"];
        put: operations["categories_update"];
        post?: never;
        delete: operations["categories_destroy"];
        options?: never;
        head?: never;
        patch: operations["categories_partial_update"];
        trace?: never;
    };
    "/api/contact/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enviar mensaje de contacto
         * @description Endpoint público para enviar mensajes de contacto.
         */
        post: operations["contact_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favorites/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar favoritos del usuario autenticado
         * @description Favoritos privados del cliente autenticado (lectura y merge de invitado).
         */
        get: operations["favorites_list"];
        put?: never;
        /**
         * Fusionar favoritos de invitado (sin duplicados)
         * @description Favoritos privados del cliente autenticado (lectura y merge de invitado).
         */
        post: operations["favorites_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favorites/{product_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Eliminar un favorito por producto
         * @description Elimina un favorito del cliente autenticado.
         */
        delete: operations["favorites_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["orders_list"];
        put?: never;
        post: operations["orders_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["orders_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/by-order-number/{order_number}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Endpoint seguro para consultar una orden por order_number.
         *     Requiere propietario, staff o cookie de capacidad válida.
         */
        get: operations["orders_by_order_number_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/by-order-number/{order_number}/access/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["orders_by_order_number_access_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/quote/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["orders_quote_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/{transaction_id}/mock-approve/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aprobar pago mock (solo desarrollo)
         * @description Aprueba la transacción mock pendiente y marca el pedido como pagado.
         */
        post: operations["payments_mock_approve_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/initiate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar proceso de pago
         * @description Recibe el order_id, registra el intento mock y devuelve la URL de pago.
         */
        post: operations["payments_initiate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["products_list"];
        put?: never;
        /** @description Crear un producto y registrar un movimiento de stock inicial si se proporciona current_stock */
        post: operations["products_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["products_retrieve"];
        put: operations["products_update"];
        post?: never;
        delete: operations["products_destroy"];
        options?: never;
        head?: never;
        patch: operations["products_partial_update"];
        trace?: never;
    };
    "/api/shipping/comunas/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar todas las comunas de Chile sueltas
         * @description Devuelve comunas activas con costo de envío positivo, aptas para cotizar y despachar.
         */
        get: operations["shipping_comunas_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipping/comunas/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar todas las comunas de Chile sueltas
         * @description Devuelve comunas activas con costo de envío positivo, aptas para cotizar y despachar.
         */
        get: operations["shipping_comunas_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipping/dispatch-options/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Opciones de despacho para una comuna
         * @description Devuelve metadatos de despacho para una comuna elegible: para Santiago, las próximas cuatro fechas de martes/jueves; fuera de Santiago, el perfil regional si existe uno único. El precio se cotiza exclusivamente desde el costo de la comuna.
         */
        get: operations["shipping_dispatch_options_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipping/regions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar regiones de Chile con sus comunas
         * @description Devuelve las 16 regiones oficiales ordenadas de Norte a Sur, incluyendo solo comunas activas con costo de envío positivo.
         */
        get: operations["shipping_regions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipping/regions/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar regiones de Chile con sus comunas
         * @description Devuelve las 16 regiones oficiales ordenadas de Norte a Sur, incluyendo solo comunas activas con costo de envío positivo.
         */
        get: operations["shipping_regions_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock-movements/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stock_movements_list"];
        put?: never;
        /** @description Crear un movimiento de stock */
        post: operations["stock_movements_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock-movements/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stock_movements_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suppliers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["suppliers_list"];
        put?: never;
        post: operations["suppliers_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suppliers/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["suppliers_retrieve"];
        put: operations["suppliers_update"];
        post?: never;
        delete: operations["suppliers_destroy"];
        options?: never;
        head?: never;
        patch: operations["suppliers_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddToCart: {
            product_id: number;
            quantity: number;
        };
        Cart: {
            readonly id: number;
            /**
             * Fecha de creación
             * Format: date-time
             */
            readonly created_at: string;
            /**
             * Fecha de actualización
             * Format: date-time
             */
            readonly updated_at: string;
            readonly items: components["schemas"]["CartItem"][];
            readonly monto_total_final: number;
            readonly subtotal: number;
            readonly shipping_cost: number | null;
            readonly total: number | null;
            readonly free_shipping_progress: number;
            readonly free_shipping_threshold: number;
        };
        CartItem: {
            /** Carro */
            cart: number;
            readonly product: components["schemas"]["Product"];
            /**
             * Cantidad
             * Format: int64
             */
            quantity?: number;
            readonly subtotal: number;
        };
        Category: {
            readonly id: number;
            /** Nombre */
            name: string;
            /** Descripción */
            description?: string | null;
            /** Categoría padre */
            parent?: number | null;
            readonly subcategories: string;
        };
        Comuna: {
            readonly id: number;
            /** Nombre */
            name: string;
            /**
             * Costo de envío
             * Format: int64
             * @description Costo de envío en CLP para esta comuna
             */
            shipping_cost?: number;
            /** @description Indica si realizamos envíos a esta comuna */
            is_active?: boolean;
        };
        ContactMessage: {
            readonly id: number;
            /** Nombre */
            name: string;
            /**
             * Correo electrónico
             * Format: email
             */
            email: string;
            /** Asunto */
            subject: string;
            /** Mensaje */
            body: string;
            /** Estado */
            readonly status: components["schemas"]["ContactMessageStatusEnum"];
            /**
             * Fecha de envío
             * Format: date-time
             */
            readonly created_at: string;
        };
        ContactMessageResponse: {
            id: number;
            status: string;
        };
        /**
         * @description * `NEW` - Nuevo
         *     * `READ` - Leído
         *     * `RESOLVED` - Resuelto
         * @enum {string}
         */
        ContactMessageStatusEnum: "NEW" | "READ" | "RESOLVED";
        /**
         * @description * `standard` - Entrega Estándar
         *     * `special` - Entrega Especial
         * @enum {string}
         */
        DeliveryKindEnum: "standard" | "special";
        /**
         * @description Read-only dispatch options for a selected destination comuna.
         *
         *     Santiago comunas expose the next four future Tuesday/Thursday dates;
         *     non-Santiago comunas expose the single applicable regional option.
         *     Exactly one of ``dates``/``shipping_option`` is populated per mode.
         */
        DispatchOptions: {
            readonly comuna_id: number;
            readonly mode: components["schemas"]["ModeEnum"];
            readonly dates: string[] | null;
            readonly shipping_option: components["schemas"]["RegionalDispatchOption"] | null;
        };
        Favorite: {
            readonly id: number;
            /** Producto */
            readonly product: number;
            /**
             * Fecha de creación
             * Format: date-time
             */
            readonly created_at: string;
        };
        FavoriteMerge: {
            product_ids: number[];
        };
        GuestAccess: {
            token: string;
            /** Format: date-time */
            expires_at: string;
        };
        GuestOrderItem: {
            product_id: number;
            quantity: number;
        };
        GuestQuoteLine: {
            product_id: number;
            product_name: string;
            quantity: number;
            unit_price: number;
            line_total: number;
        };
        GuestQuoteResponse: {
            items: components["schemas"]["GuestQuoteLine"][];
            subtotal: number;
            shipping_cost?: number;
            total?: number;
            revision: string;
        };
        InitiatePayment: {
            order_id: number;
        };
        InitiatePaymentResponse: {
            transaction_id: number;
            order_id: number;
            amount: number;
            payment_url: string;
            gateway_reference: string;
        };
        MockApproveResponse: {
            transaction_id: number;
            order_id: number;
            status: string;
            order_status: string;
        };
        /**
         * @description * `santiago` - santiago
         *     * `regional` - regional
         * @enum {string}
         */
        ModeEnum: "santiago" | "regional";
        /**
         * @description * `IN` - Entrada
         *     * `OUT` - Salida
         * @enum {string}
         */
        MovementTypeEnum: "IN" | "OUT";
        Order: {
            readonly id: number;
            readonly order_number: string;
            phone?: string;
            comuna?: number;
            comuna_name?: string;
            readonly comuna_display: string;
            region_name?: string;
            /** Dirección de despacho */
            shipping_address: string;
            /** Depto / oficina */
            apartment_office?: string | null;
            /**
             * Correo invitado
             * Format: email
             */
            guest_email?: string | null;
            /** Nombre invitado */
            guest_name?: string | null;
            /** @description Lista de productos para invitados */
            guest_items?: components["schemas"]["GuestOrderItem"][];
            /** @description Signed quote revision explicitly confirmed by a guest. */
            confirmed_revision?: string | null;
            payment_method?: components["schemas"]["PaymentMethodEnum"];
            readonly guest_access: components["schemas"]["GuestAccess"] | null;
            /** Subtotal productos */
            readonly subtotal: number;
            /** Costo de envío */
            readonly shipping_cost: number;
            /** Total final */
            readonly total: number;
            /** Estado del pedido */
            readonly status: components["schemas"]["OrderStatusEnum"];
            /**
             * Fecha de creación
             * Format: date-time
             */
            readonly created_at: string;
            /**
             * Transportista
             * @description Empresa de transporte encargada del envío.
             */
            readonly carrier: string;
            /**
             * Número de seguimiento
             * @description Código de rastreo proporcionado por el transportista.
             */
            readonly tracking_number: string | null;
            readonly items: components["schemas"]["OrderItem"][];
            delivery_kind?: components["schemas"]["DeliveryKindEnum"];
            /** Format: date */
            requested_dispatch_date?: string | null;
            readonly delivery_gate_status: string;
            /**
             * Fecha estimada de entrega
             * Format: date
             * @description Fecha estimada de entrega registrada por el staff al despachar.
             */
            readonly estimated_delivery_date: string | null;
            /**
             * Fecha de despacho
             * Format: date-time
             * @description Momento en que el pedido fue despachado.
             */
            readonly dispatched_at: string | null;
            shipping_option_id?: number | null;
        };
        OrderCreate: {
            phone?: string;
            comuna?: number;
            comuna_name?: string;
            region_name?: string;
            /** Dirección de despacho */
            shipping_address: string;
            /** Depto / oficina */
            apartment_office?: string | null;
            /**
             * Correo invitado
             * Format: email
             */
            guest_email?: string | null;
            /** Nombre invitado */
            guest_name?: string | null;
            /** @description Lista de productos para invitados */
            guest_items?: components["schemas"]["GuestOrderItem"][];
            /** @description Signed quote revision explicitly confirmed by a guest. */
            confirmed_revision?: string | null;
            payment_method?: components["schemas"]["PaymentMethodEnum"];
            delivery_kind?: components["schemas"]["DeliveryKindEnum"];
            /** Format: date */
            requested_dispatch_date?: string | null;
            shipping_option_id?: number | null;
        };
        OrderItem: {
            readonly id: number;
            /** Producto */
            readonly product_id: number | null;
            /** Nombre del producto congelado */
            product_name: string;
            /**
             * Precio unitario congelado
             * Format: int64
             */
            price: number;
            /**
             * Cantidad
             * Format: int64
             */
            quantity: number;
            readonly subtotal: number;
        };
        /**
         * @description * `PENDING` - Pendiente de Pago
         *     * `PAID` - Pagado / Listo para Despacho
         *     * `SHIPPED` - Enviado a Destino
         *     * `DELIVERED` - Entregado al Cliente
         *     * `CANCELLED` - Cancelado / Anulado
         * @enum {string}
         */
        OrderStatusEnum: "PENDING" | "PAID" | "SHIPPED" | "DELIVERED" | "CANCELLED";
        PaginatedCategoryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Category"][];
        };
        PaginatedOrderList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Order"][];
        };
        PaginatedProductList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Product"][];
        };
        PaginatedStockMovementList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["StockMovement"][];
        };
        PaginatedSupplierList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Supplier"][];
        };
        PatchedCategory: {
            readonly id?: number;
            /** Nombre */
            name?: string;
            /** Descripción */
            description?: string | null;
            /** Categoría padre */
            parent?: number | null;
            readonly subcategories?: string;
        };
        PatchedProduct: {
            readonly id?: number;
            /** Nombre */
            name?: string;
            sku?: string | null;
            /** Format: int64 */
            price?: number;
            /** Descripción */
            description?: string | null;
            readonly image?: string | null;
            readonly image_original?: string | null;
            readonly images?: components["schemas"]["ProductImage"][];
            /** Gradiente */
            gradient?: string;
            /** Icono */
            icon?: string;
            badge?: string | null;
            /** Características */
            features?: unknown;
            category?: number;
            readonly stock?: number;
            readonly experience_level?: number;
            /** Format: int64 */
            current_stock?: number;
            /** Format: int64 */
            minimum_stock?: number;
            /** Proveedor */
            supplier?: number;
            /**
             * Fecha de creación
             * Format: date-time
             */
            readonly created_at?: string;
            /**
             * Fecha de actualización
             * Format: date-time
             */
            readonly updated_at?: string;
        };
        PatchedProfilePhone: {
            phone?: string;
        };
        PatchedSupplier: {
            readonly id?: number;
            /** Nombre */
            name?: string;
            /** Contacto */
            contact?: string;
            /**
             * Correo electrónico
             * Format: email
             */
            email?: string;
            /** Teléfono */
            phone?: string;
            /** Dirección */
            address?: string;
        };
        /**
         * @description * `webpay` - Webpay
         *     * `flow` - Flow
         *     * `mercadopago` - MercadoPago
         *     * `transfer` - Transferencia Bancaria
         * @enum {string}
         */
        PaymentMethodEnum: "webpay" | "flow" | "mercadopago" | "transfer";
        Product: {
            readonly id: number;
            /** Nombre */
            name: string;
            sku?: string | null;
            /** Format: int64 */
            price: number;
            /** Descripción */
            description?: string | null;
            readonly image: string | null;
            readonly image_original: string | null;
            readonly images: components["schemas"]["ProductImage"][];
            /** Gradiente */
            gradient?: string;
            /** Icono */
            icon?: string;
            badge?: string | null;
            /** Características */
            features?: unknown;
            category: number;
            readonly stock: number;
            readonly experience_level: number;
            /** Format: int64 */
            current_stock?: number;
            /** Format: int64 */
            minimum_stock?: number;
            /** Proveedor */
            supplier: number;
            /**
             * Fecha de creación
             * Format: date-time
             */
            readonly created_at: string;
            /**
             * Fecha de actualización
             * Format: date-time
             */
            readonly updated_at: string;
        };
        ProductImage: {
            readonly id: number;
            readonly image: string | null;
            readonly image_original: string | null;
        };
        Quote: {
            items: components["schemas"]["GuestOrderItem"][];
            comuna?: number;
        };
        QuoteError: {
            code: string;
            detail: string;
        };
        QuoteRevisionStale: {
            code: string;
            detail: string;
            refreshed_quote: components["schemas"]["GuestQuoteResponse"];
        };
        Region: {
            readonly id: number;
            /** Nombre */
            name: string;
            /**
             * Orden geográfico
             * Format: int64
             * @description Orden geográfico de la región de Norte a Sur
             */
            ordinal_number: number;
            readonly comunas: string;
        };
        /** @description The one applicable regional dispatch profile for a non-Santiago comuna. */
        RegionalDispatchOption: {
            readonly shipping_option_id: number;
            readonly key: string;
            readonly carrier: string;
            readonly min_lead_days: number;
            readonly max_lead_days: number;
        };
        Register: {
            /** Nombre */
            first_name?: string;
            /** Apellidos */
            last_name?: string;
            /** Format: email */
            email: string;
            rut?: string | null;
            phone?: string | null;
            password: string;
            password_confirm: string;
        };
        /**
         * @description 409 response body when a special-dispatch order still awaits its staff
         *     agreement: typed error code, recovery guidance, the backend-produced
         *     WhatsApp agreement link, and the client poll interval in seconds.
         */
        SpecialDeliveryAgreementRequiredError: {
            code: string;
            detail: string;
            /** Format: uri */
            whatsapp_url: string;
            poll_after_seconds: number;
        };
        StockMovement: {
            readonly id: number;
            /** Producto */
            product: number;
            /** Tipo de movimiento */
            movement_type: components["schemas"]["MovementTypeEnum"];
            /**
             * Cantidad
             * Format: int64
             */
            quantity: number;
            /**
             * Fecha y hora
             * Format: date-time
             */
            readonly timestamp: string;
            readonly alert: string;
        };
        Supplier: {
            readonly id: number;
            /** Nombre */
            name: string;
            /** Contacto */
            contact: string;
            /**
             * Correo electrónico
             * Format: email
             */
            email: string;
            /** Teléfono */
            phone: string;
            /** Dirección */
            address: string;
        };
        TokenObtainPair: {
            email: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        UserMe: {
            readonly id: number;
            /** Nombre */
            first_name?: string;
            /** Apellidos */
            last_name?: string;
            /** Format: email */
            email: string;
            rut?: string | null;
            phone?: string | null;
            readonly is_admin: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_csrf_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message?: string;
                    };
                };
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMe"];
                };
            };
        };
    };
    auth_me_phone_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProfilePhone"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProfilePhone"];
                "multipart/form-data": components["schemas"]["PatchedProfilePhone"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMe"];
                };
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Register"];
                "application/x-www-form-urlencoded": components["schemas"]["Register"];
                "multipart/form-data": components["schemas"]["Register"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Register"];
                };
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    cart_me_retrieve: {
        parameters: {
            query?: {
                /** @description ID de la comuna de entrega para el estimado de envío autoritativo. */
                comuna?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
        };
    };
    cart_me_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddToCart"];
                "application/x-www-form-urlencoded": components["schemas"]["AddToCart"];
                "multipart/form-data": components["schemas"]["AddToCart"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
        };
    };
    cart_me_destroy: {
        parameters: {
            query: {
                product_id: number;
                quantity: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
        };
    };
    categories_list: {
        parameters: {
            query?: {
                /** @description Un número de página dentro del conjunto de resultados paginado. */
                page?: number;
                /** @description Un término de búsqueda. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCategoryList"];
                };
            };
        };
    };
    categories_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Category"];
                "application/x-www-form-urlencoded": components["schemas"]["Category"];
                "multipart/form-data": components["schemas"]["Category"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    categories_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Categoría. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    categories_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Categoría. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Category"];
                "application/x-www-form-urlencoded": components["schemas"]["Category"];
                "multipart/form-data": components["schemas"]["Category"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    categories_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Categoría. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    categories_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Categoría. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCategory"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCategory"];
                "multipart/form-data": components["schemas"]["PatchedCategory"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    contact_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactMessage"];
                "application/x-www-form-urlencoded": components["schemas"]["ContactMessage"];
                "multipart/form-data": components["schemas"]["ContactMessage"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactMessageResponse"];
                };
            };
        };
    };
    favorites_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Favorite"][];
                };
            };
        };
    };
    favorites_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FavoriteMerge"];
                "application/x-www-form-urlencoded": components["schemas"]["FavoriteMerge"];
                "multipart/form-data": components["schemas"]["FavoriteMerge"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Favorite"][];
                };
            };
        };
    };
    favorites_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    orders_list: {
        parameters: {
            query?: {
                /** @description Un número de página dentro del conjunto de resultados paginado. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedOrderList"];
                };
            };
        };
    };
    orders_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description Clave de idempotencia del checkout (máx. 64 caracteres). */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["OrderCreate"];
                "multipart/form-data": components["schemas"]["OrderCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteRevisionStale"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteError"];
                };
            };
        };
    };
    orders_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Pedido. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
        };
    };
    orders_by_order_number_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
        };
    };
    orders_by_order_number_access_create: {
        parameters: {
            query?: never;
            header: {
                "X-Order-Capability": string;
            };
            path: {
                order_number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    orders_quote_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Quote"];
                "application/x-www-form-urlencoded": components["schemas"]["Quote"];
                "multipart/form-data": components["schemas"]["Quote"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuestQuoteResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteError"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteError"];
                };
            };
        };
    };
    payments_mock_approve_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MockApproveResponse"];
                };
            };
        };
    };
    payments_initiate_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description Clave de idempotencia del intento de pago (máx. 64 caracteres). */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitiatePayment"];
                "application/x-www-form-urlencoded": components["schemas"]["InitiatePayment"];
                "multipart/form-data": components["schemas"]["InitiatePayment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InitiatePaymentResponse"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialDeliveryAgreementRequiredError"];
                };
            };
        };
    };
    products_list: {
        parameters: {
            query?: {
                /** @description Múltiples valores separados por comas. */
                category?: number[];
                /** @description Múltiples valores separados por comas. */
                experience_level?: number[];
                experience_level__gte?: number;
                experience_level__lte?: number;
                max_price?: string;
                min_price?: string;
                /** @description Qué campo usar para ordenar los resultados. */
                ordering?: string;
                /** @description Un número de página dentro del conjunto de resultados paginado. */
                page?: number;
                /** @description Un término de búsqueda. */
                search?: string;
                sku?: string;
                supplier?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProductList"];
                };
            };
        };
    };
    products_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Product"];
                "application/x-www-form-urlencoded": components["schemas"]["Product"];
                "multipart/form-data": components["schemas"]["Product"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    products_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Producto. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    products_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Producto. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Product"];
                "application/x-www-form-urlencoded": components["schemas"]["Product"];
                "multipart/form-data": components["schemas"]["Product"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    products_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Producto. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    products_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Producto. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProduct"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProduct"];
                "multipart/form-data": components["schemas"]["PatchedProduct"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    shipping_comunas_list: {
        parameters: {
            query?: {
                region?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comuna"][];
                };
            };
        };
    };
    shipping_comunas_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Comuna. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comuna"];
                };
            };
        };
    };
    shipping_dispatch_options_retrieve: {
        parameters: {
            query: {
                /** @description ID de la comuna de destino para calcular las opciones de despacho. */
                comuna: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispatchOptions"];
                };
            };
        };
    };
    shipping_regions_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Region"][];
                };
            };
        };
    };
    shipping_regions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Región. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Region"];
                };
            };
        };
    };
    stock_movements_list: {
        parameters: {
            query?: {
                /** @description Un número de página dentro del conjunto de resultados paginado. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedStockMovementList"];
                };
            };
        };
    };
    stock_movements_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockMovement"];
                "application/x-www-form-urlencoded": components["schemas"]["StockMovement"];
                "multipart/form-data": components["schemas"]["StockMovement"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockMovement"];
                };
            };
        };
    };
    stock_movements_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Movimiento de Stock. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockMovement"];
                };
            };
        };
    };
    suppliers_list: {
        parameters: {
            query?: {
                /** @description Un número de página dentro del conjunto de resultados paginado. */
                page?: number;
                /** @description Un término de búsqueda. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSupplierList"];
                };
            };
        };
    };
    suppliers_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Supplier"];
                "application/x-www-form-urlencoded": components["schemas"]["Supplier"];
                "multipart/form-data": components["schemas"]["Supplier"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Supplier"];
                };
            };
        };
    };
    suppliers_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Proveedor. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Supplier"];
                };
            };
        };
    };
    suppliers_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Proveedor. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Supplier"];
                "application/x-www-form-urlencoded": components["schemas"]["Supplier"];
                "multipart/form-data": components["schemas"]["Supplier"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Supplier"];
                };
            };
        };
    };
    suppliers_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Proveedor. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    suppliers_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Proveedor. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSupplier"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSupplier"];
                "multipart/form-data": components["schemas"]["PatchedSupplier"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Supplier"];
                };
            };
        };
    };
}
