# Generated by Django 6.0.6 on 2026-06-21 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_alter_category_options_alter_product_options_and_more'),
        ('shipping', '0003_alter_comuna_name_alter_comuna_region_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='correo invitado')),
                ('guest_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='nombre invitado')),
                ('phone', models.CharField(max_length=20, verbose_name='teléfono de contacto')),
                ('shipping_address', models.CharField(max_length=255, verbose_name='dirección de despacho')),
                ('apartment_office', models.CharField(blank=True, max_length=50, null=True, verbose_name='depto / oficina')),
                ('subtotal', models.PositiveIntegerField(verbose_name='subtotal productos')),
                ('shipping_cost', models.PositiveIntegerField(verbose_name='costo de envío')),
                ('total', models.PositiveIntegerField(verbose_name='total final')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Pago'), ('PAID', 'Pagado / Listo para Despacho'), ('SHIPPED', 'Enviado a Destino'), ('DELIVERED', 'Entregado al Cliente'), ('CANCELLED', 'Cancelado / Anulado')], default='PENDING', max_length=15, verbose_name='estado del pedido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shipping.comuna', verbose_name='comuna de entrega')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='nombre del producto congelado')),
                ('price', models.PositiveIntegerField(verbose_name='precio unitario congelado')),
                ('quantity', models.PositiveIntegerField(verbose_name='cantidad')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='pedido')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'Detalle del Pedido',
                'verbose_name_plural': 'Detalles de los Pedidos',
            },
        ),
    ]
