# Generated by Django 6.0.6 on 2026-07-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, help_text='Identificador público del pedido (ej: CS-XXXXXXX).', max_length=20, null=True, unique=True, verbose_name='número de pedido'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('webpay', 'Webpay'), ('flow', 'Flow'), ('mercadopago', 'MercadoPago'), ('transfer', 'Transferencia Bancaria')], default='webpay', max_length=50, verbose_name='método de pago'),
        ),
    ]
