# Generated by Django 6.0.6 on 2026-07-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_number_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.CharField(default='Chilexpress', help_text='Empresa de transporte encargada del envío.', max_length=100, verbose_name='transportista'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Código de rastreo proporcionado por el transportista.', max_length=100, null=True, verbose_name='número de seguimiento'),
        ),
    ]
