# Generated by Django 6.0.6 on 2026-08-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_carrier_order_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_access_digest',
            field=models.CharField(blank=True, help_text='SHA-256 hex digest del token de acceso. Nunca almacenar el token en claro.', max_length=64, null=True, verbose_name='hash de acceso de invitado'),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_access_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de expiración del acceso'),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_access_issued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de emisión del acceso'),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_access_revoked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de revocación del acceso'),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_access_version',
            field=models.PositiveIntegerField(default=0, verbose_name='versión del acceso'),
        ),
    ]
