# Generated by Django 6.0.6 on 2026-08-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_guest_access_digest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_key',
            field=models.CharField(blank=True, help_text='Clave idempotente del checkout; el reintento con la misma clave devuelve el mismo pedido.', max_length=64, null=True, unique=True, verbose_name='clave de checkout'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_kind',
            field=models.CharField(choices=[('standard', 'Entrega Estándar'), ('special', 'Entrega Especial')], default='standard', help_text='standard: fechas regulares de despacho; special: requiere acuerdo previo por WhatsApp.', max_length=20, verbose_name='tipo de entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, help_text='Momento en que el pedido fue despachado.', null=True, verbose_name='fecha de despacho'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, help_text='Fecha estimada de entrega registrada por el staff al despachar.', null=True, verbose_name='fecha estimada de entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='requested_dispatch_date',
            field=models.DateField(blank=True, help_text='Fecha especial de despacho solicitada por el cliente.', null=True, verbose_name='fecha de despacho solicitada'),
        ),
        migrations.AddField(
            model_name='order',
            name='special_delivery_agreed_at',
            field=models.DateTimeField(blank=True, help_text='Momento en que el staff confirmó el acuerdo especial; sin esto el pago permanece bloqueado.', null=True, verbose_name='acuerdo de entrega especial'),
        ),
    ]
