# Generated by Django 6.0.6 on 2026-08-12 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_checkout_delivery_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('payment_confirmation', 'Confirmación de Pago'), ('dispatch', 'Despacho del Pedido')], max_length=30, verbose_name='evento')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviado'), ('FAILED', 'Fallido')], default='PENDING', max_length=10, verbose_name='estado')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='intentos')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='último error')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='próximo reintento')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de envío')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'unique_together': {('order', 'event')},
            },
        ),
    ]
