# Generated by Django 6.0.6 on 2026-08-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_notificationdelivery'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['status', 'next_retry_at'], name='orders_notif_status_next_retry'),
        ),
    ]
