# Generated by Django 6.0.6 on 2026-09-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_backfill_inventory_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Momento en que el pedido fue marcado como entregado.', null=True, verbose_name='fecha de entrega'),
        ),
    ]
