# Generated by Django 6.0.6 on 2026-09-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_email_access_revoked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de revocación del enlace de correo'),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_email_access_version',
            field=models.PositiveIntegerField(default=1, verbose_name='versión del enlace de correo'),
        ),
    ]
