# Generated by Django 5.2.6 on 2026-09-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_guest_email_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdelivery',
            name='event',
            field=models.CharField(choices=[('payment_confirmation', 'Confirmación de Pago'), ('dispatch', 'Despacho del Pedido'), ('delivered', 'Entrega del Pedido')], max_length=30, verbose_name='evento'),
        ),
    ]
