# Generated by Django 6.0.6 on 2026-06-19 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ordinal_number', models.IntegerField(help_text='Orden geográfico de la región de Norte a Sur')),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'ordering': ['ordinal_number'],
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shipping_cost', models.PositiveIntegerField(default=0, help_text='Costo de envío en CLP para esta comuna')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si realizamos envíos a esta comuna')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='shipping.region')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'ordering': ['name'],
                'unique_together': {('name', 'region')},
            },
        ),
    ]
