# Generated by Django 6.0.6 on 2026-06-21 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_auto_20260619_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='shipping.region', verbose_name='región'),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='shipping_cost',
            field=models.PositiveIntegerField(default=0, help_text='Costo de envío en CLP para esta comuna', verbose_name='costo de envío'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='region',
            name='ordinal_number',
            field=models.IntegerField(help_text='Orden geográfico de la región de Norte a Sur', verbose_name='orden geográfico'),
        ),
    ]
