# Generated by Django 6.0.6 on 2026-08-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_alter_comuna_name_alter_comuna_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalShippingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='regional', help_text='Clave única del singleton regional.', max_length=50, unique=True, verbose_name='clave')),
                ('carrier', models.CharField(max_length=100, verbose_name='transportista')),
                ('tariff', models.PositiveIntegerField(help_text='Tarifa de envío en CLP para la opción regional.', verbose_name='tarifa CLP')),
                ('min_lead_days', models.PositiveIntegerField(help_text='Plazo mínimo de entrega en días para la opción regional.', verbose_name='plazo mínimo (días)')),
                ('max_lead_days', models.PositiveIntegerField(help_text='Plazo máximo de entrega en días para la opción regional.', verbose_name='plazo máximo (días)')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la opción regional está disponible para nuevos despachos.', verbose_name='activa')),
            ],
            options={
                'verbose_name': 'Opción de Envío Regional',
                'verbose_name_plural': 'Opciones de Envío Regional',
                'ordering': ['key'],
            },
        ),
    ]
