# Generated by Django 6.0.6 on 2026-06-28 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='monto de la transacción')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Pago'), ('APPROVED', 'Aprobado / Exitoso'), ('REJECTED', 'Rechazado / Fallido')], default='PENDING', max_length=15, verbose_name='estado de transacción')),
                ('gateway_reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de referencia de la pasarela')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='método de pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de intento')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de respuesta')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'Transacción de Pago',
                'verbose_name_plural': 'Transacciones de Pagos',
                'ordering': ['-created_at'],
            },
        ),
    ]
