# Generated by Django 6.0.6 on 2026-08-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_checkout_delivery_fields'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Clave única por pedido que hace idempotentes los reintentos de pago.', max_length=255, null=True, verbose_name='clave de idempotencia'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider',
            field=models.CharField(blank=True, help_text='Identificador del proveedor de pago que gestiona el intento.', max_length=50, null=True, verbose_name='proveedor de pago'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('order', 'idempotency_key'), name='unique_transaction_order_idempotency_key'),
        ),
    ]
