# Generated by Django 6.0.6 on 2026-06-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
