# Generated by Django 6.0.6 on 2026-07-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='badge'),
        ),
        migrations.AddField(
            model_name='product',
            name='experience_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, verbose_name='nivel de experiencia'),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.JSONField(default=list, verbose_name='características'),
        ),
        migrations.AddField(
            model_name='product',
            name='gradient',
            field=models.CharField(default='from-gray-500 to-gray-700', max_length=200, verbose_name='gradiente'),
        ),
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.CharField(default='box', max_length=100, verbose_name='icono'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SKU'),
        ),
    ]
