# Generated by Django 6.0.6 on 2026-07-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_sku_ui_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='experience_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], db_index=True, default=3, verbose_name='nivel de experiencia'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(db_index=True),
        ),
    ]
